### ISSUE TITLE
Verander a elementen naar button

### ISSUE THREAD

**Issue by J3SS3HVA** [Saif8599/fix-the-flow-interactive-website#24]
`a` is een hyperlink element. het is niet bedoeld voor interacties maar om de gebruiker naar een andere pagina te brengen of een andere website. Gebruik de button element

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a

goed dat je gebruik maakt van comments

**Comment by Saif8599** [comment]
https://github.com/Saif8599/fix-the-flow-interactive-website/commit/a3020326ae6f70edde71d486ee50a016ba9397f4
