### ISSUE TITLE
Design-review:

### ISSUE THREAD

**Issue by Clarice-COD** [Saif8599/fix-the-flow-interactive-website#28]
Feedforward:
Het is begrijpelijk waarnaar de knoppen leiden. 

Feedback:
De feedback ontbreekt. Denk bijvoorbeeld aan wanneer je op de knop klikt de kleur veranderd zodat je weet dat er iets gebeurd. 

interactie idee:
Misschien is het een leuk idee wanneer je de knoppen hovert, ze net iets groter worden zodat je weet dat het klikbaar is.

@brancovanbeek @divaniNL

**Comment by Saif8599** [comment]
https://github.com/Saif8599/fix-the-flow-interactive-website/commit/a3020326ae6f70edde71d486ee50a016ba9397f4
