### ISSUE TITLE
Leg uit waar de pagina over gaat

### ISSUE THREAD

**Issue by KoopReynders** [Saif8599/fix-the-flow-interactive-website#29]
Onder de titel van de pagina mag je best de pagina uitleggen in 2 zinnen, dat is ook feedback voor de gebruiker.

**Comment by Saif8599** [comment]
https://github.com/Saif8599/fix-the-flow-interactive-website/commit/6e49280768c2f0d964c01275e27d5534460f7f9a

**Comment by KoopReynders** [comment]
De regels in de tekst lijken nog wat te lang. Misschien de paragraaf een max-width meegeven?
<img width="1064" alt="image" src="https://github.com/user-attachments/assets/1e5991a8-8fd2-4271-beb7-17184ab77d6a" />
