### ISSUE TITLE
Filter systeem uitleggen

### ISSUE THREAD

**Issue by KoopReynders** [Saif8599/fix-the-flow-interactive-website#30]
Het is logischer om  filter systeem onder de titel 'All' te zetten. 
En leg het filter systeem ook uit aan de gebruiker. 

Feedback en feedforward na het filteren ontbreekt nog. Zoals de active state op de filter buttons. 
Dit is goede feedback "Webinars voor de categorie "NeuroOncology". Zou mooi zijn als je dit helemaal kan bouwen.

**Comment by Saif8599** [comment]
https://github.com/Saif8599/fix-the-flow-interactive-website/commit/2b26da007704a461d52498bdc16ecd8df74b3b8b#diff-8579a8a9a523d32b93da87e77b7317242a66cbb895cdea02fcef244d6d07837fR59-R68

**Comment by KoopReynders** [comment]
Als je een issue sluit, dan nog even schrijven wat je hebt gedaan. 
Ik denk te zien dat het filter nog geen uitleg heeft? 
Je bent al wel bezig met states op de filter buttons. (hebben we vandaag besproken)

**Comment by KoopReynders** [comment]
Als je hiermee verder gaat, zoals we vandaag hebben besproken, kun je de issue weer openen.

**Comment by Saif8599** [comment]
https://github.com/Saif8599/fix-the-flow-interactive-website/commit/7e2cd27cf8dcb676cc4a6ce33765993cc557503f

resetSubject en HideInactiveSubjects funties verwijderd. Nu kan de gebruiken zien op welke subject hij sorteert zonder dat alle subject verdwijnen. Subjects verwijderen doormiddel van de active hover leidt naar "All" subject
